In [6]:
path = "master/data_set/datingTestSet.txt"
import numpy as np

In [9]:
data = []
labels = []
open_file = open(path,mode = 'r',encoding='GBK')
STR = open_file.read()
lines = STR.split('\n')
for line in lines:
    f_1 = line.split('\t')
    x1,x2,x3,label = float(f_1[0]),float(f_1[1]),float(f_1[2]),f_1[3]
    data.append([x1,x2,x3])
    labels.append(label)
    
data = np.array(data)
labels = np.array(labels)

In [11]:
print(labels)

['largeDoses' 'smallDoses' 'didntLike' 'didntLike' 'didntLike' 'didntLike'
 'largeDoses' 'largeDoses' 'didntLike' 'largeDoses' 'didntLike'
 'didntLike' 'smallDoses' 'didntLike' 'didntLike' 'didntLike' 'didntLike'
 'didntLike' 'smallDoses' 'largeDoses' 'smallDoses' 'didntLike'
 'smallDoses' 'largeDoses' 'smallDoses' 'largeDoses' 'smallDoses'
 'largeDoses' 'smallDoses' 'didntLike' 'largeDoses' 'didntLike'
 'largeDoses' 'didntLike' 'smallDoses' 'didntLike' 'didntLike'
 'smallDoses' 'largeDoses' 'largeDoses' 'didntLike' 'smallDoses'
 'largeDoses' 'largeDoses' 'largeDoses' 'didntLike' 'didntLike'
 'didntLike' 'didntLike' 'smallDoses' 'smallDoses' 'didntLike'
 'largeDoses' 'smallDoses' 'smallDoses' 'smallDoses' 'smallDoses'
 'largeDoses' 'didntLike' 'smallDoses' 'didntLike' 'smallDoses'
 'smallDoses' 'smallDoses' 'smallDoses' 'smallDoses' 'largeDoses'
 'smallDoses' 'largeDoses' 'didntLike' 'smallDoses' 'largeDoses'
 'smallDoses' 'smallDoses' 'didntLike' 'largeDoses' 'didntLike'
 'didntLike' 

In [12]:
a = [1,2,3]
a[:-1]

[1, 2]

In [13]:
a[0:2]

[1, 2]

In [17]:
max_ = np.max(data,axis=0)
min_ = np.min(data,axis=0)
print(max_)
print(min_)

[9.1273000e+04 2.0919349e+01 1.6955170e+00]
[0.       0.       0.001156]


In [18]:
new_data = (data - min_) / (max_ - min_)

In [19]:
new_data

array([[0.44832535, 0.39805139, 0.56233353],
       [0.15873259, 0.34195467, 0.98724416],
       [0.28542943, 0.06892523, 0.47449629],
       ...,
       [0.29115949, 0.50910294, 0.51079493],
       [0.52711097, 0.43665451, 0.4290048 ],
       [0.47940793, 0.3768091 , 0.78571804]])

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test = train_test_split(new_data,labels,test_size=0.3,random_state=42)

In [23]:
x_test.shape

(300, 3)

In [24]:
x_train.shape

(700, 3)

In [25]:
y_test.shape

(300,)

In [26]:
y_train.shape

(700,)

In [27]:
 def KNN_model(x_train,x_test,y_train,y_test,K):
        data = x_test(i)
        distance = np.power(np.sum((data - x_train)**2,axis=1),0.5)
        sort_k = np.argsort(distance)[:K]
        
    
    